python src/run_experiment.py \
        --steering \
        --config config/default.yaml \
        --steer_layers layers.29\
        --topk 100 \
        --device cuda:2 \
        --get_index_type Reason \
        --steering_target_strategy direct \
        --token_pos 1 \
        --steer_n_steps 1 \
        --steer_alpha 100.0